"""
Presenter

Formats the final weekly digest as:
  1. A rich terminal string (for CLI use)
  2. A plain dict / Markdown string (for Streamlit UI use)
"""

from datetime import datetime
from agents.context_summarizer import ResearchProfile
from agents.ranker import RankedPaper


_LABEL_EMOJI = {
    "research": "[RESEARCH]",
    "coursework": "[COURSEWORK]",
    "project": "[PROJECT]",
}

_DEPTH_EMOJI = {
    "skim (10 min)": "Skim (10 min)",
    "deep read": "Deep Read",
    "save for later": "Save for Later",
}


def format_terminal(profile: ResearchProfile, ranked: list[RankedPaper]) -> str:
    """
    Returns a nicely formatted string for printing in the terminal.
    """
    lines = []
    now = datetime.now().strftime("%A, %B %d %Y")
    lines.append("=" * 70)
    lines.append(f"  WEEKLY RESEARCH DIGEST  |  {now}")
    lines.append("=" * 70)

    lines.append("\nYOUR WEEK IN BRIEF")
    lines.append("-" * 40)
    lines.append(profile.context_summary)

    lines.append("\nACTIVE TOPICS")
    for t in profile.active_topics:
        lines.append(f"  * {t}")

    lines.append("\n" + "=" * 70)
    lines.append("  TOP PAPER PICKS FOR THIS WEEK")
    lines.append("=" * 70)

    for i, rp in enumerate(ranked, start=1):
        p = rp.paper
        label = _LABEL_EMOJI.get(rp.relevance_label, rp.relevance_label.upper())
        depth = _DEPTH_EMOJI.get(rp.read_depth, rp.read_depth)

        lines.append(f"\n{i}. {p.title}")
        lines.append(f"   {label}  |  {depth}  |  {p.date}  |  {p.source.replace('_', ' ').title()}")
        if p.authors:
            lines.append(f"   Authors: {', '.join(p.authors[:3])}")
        lines.append(f"   URL: {p.url}")
        lines.append(f"\n   Why it matters for you:")
        # Word-wrap explanation at ~65 chars
        words = rp.explanation.split()
        line_buf = "   "
        for word in words:
            if len(line_buf) + len(word) + 1 > 68:
                lines.append(line_buf)
                line_buf = "   " + word
            else:
                line_buf += (" " if line_buf.strip() else "") + word
        if line_buf.strip():
            lines.append(line_buf)

    lines.append("\n" + "=" * 70)
    lines.append("  Generated by your Research Recommendation Agent")
    lines.append("=" * 70 + "\n")

    return "\n".join(lines)


def format_markdown(profile: ResearchProfile, ranked: list[RankedPaper]) -> str:
    """
    Returns the digest as a Markdown string (for Streamlit st.markdown).
    """
    now = datetime.now().strftime("%A, %B %d %Y")
    lines = []
    lines.append(f"# Weekly Research Digest — {now}")
    lines.append(f"\n> {profile.context_summary}")

    lines.append("\n## Your Active Topics")
    for t in profile.active_topics:
        lines.append(f"- {t}")

    lines.append("\n---\n## Top Paper Picks")

    for i, rp in enumerate(ranked, start=1):
        p = rp.paper
        label = rp.relevance_label.capitalize()
        depth = rp.read_depth.capitalize()

        lines.append(f"\n### {i}. [{p.title}]({p.url})")
        lines.append(f"**{label}** | {depth} | {p.date} | {p.source.replace('_', ' ').title()}")
        if p.authors:
            lines.append(f"*{', '.join(p.authors[:3])}*")
        lines.append(f"\n{rp.explanation}")

    lines.append("\n---\n*Generated by your Research Recommendation Agent*")
    return "\n".join(lines)


def format_dict(profile: ResearchProfile, ranked: list[RankedPaper]) -> dict:
    """
    Returns a plain dict for JSON export or further processing.
    """
    return {
        "generated_at": datetime.now().isoformat(),
        "context_summary": profile.context_summary,
        "active_topics": profile.active_topics,
        "papers": [
            {
                "rank": i,
                "title": rp.paper.title,
                "url": rp.paper.url,
                "date": rp.paper.date,
                "source": rp.paper.source,
                "authors": rp.paper.authors,
                "relevance_label": rp.relevance_label,
                "explanation": rp.explanation,
                "read_depth": rp.read_depth,
                "score": round(rp.score, 4),
            }
            for i, rp in enumerate(ranked, start=1)
        ],
    }
